version: '3.8'

services:
 mysql-db:
  image: mysql:latest
  container_name: 'mysql-db'
  command: '--default-authentication-plugin=mysql_native_password'
  restart: always
  environment:
   MYSQL_DATABASE: 'personal'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'root'
   MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
   - /etc/private/mysql-data:/var/lib/mysql
